name: Trigger auto deployment for api-gateway-graphql

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/ApiGateway/dev-ops/**'
    - '.github/workflows/api-gateway-graphql-AutoDeployTrigger-46e88f01-62cb-430e-aa8a-d6757577d89d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: looselycoupledmonolith.azurecr.io
          username: ${{ secrets.APIGATEWAYGRAPHQL_REGISTRY_USERNAME }}
          password: ${{ secrets.APIGATEWAYGRAPHQL_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: looselycoupledmonolith.azurecr.io/api-gateway-graphql:${{ github.sha }}
          file: ./src/ApiGateway/dev-ops/Dockerfile
          context: ./src/ApiGateway/dev-ops/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.APIGATEWAYGRAPHQL_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n api-gateway-graphql -g loosely-coupled-monolith --server looselycoupledmonolith.azurecr.io --username  ${{ secrets.APIGATEWAYGRAPHQL_REGISTRY_USERNAME }} --password ${{ secrets.APIGATEWAYGRAPHQL_REGISTRY_PASSWORD }}
            az containerapp update -n api-gateway-graphql -g loosely-coupled-monolith --image looselycoupledmonolith.azurecr.io/api-gateway-graphql:${{ github.sha }}
